version: 2
jobs:
  build:
    working_directory: ~/blockstack
    docker:
      - image: circleci/python:2.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "integration_tests/setup.py" }}
      - run:
          command: |
            python -m virtualenv venv
            source venv/bin/activate
            pip install ./integration_tests --upgrade --upgrade-strategy only-if-needed
            pip install . --upgrade --upgrade-strategy only-if-needed
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "integration_tests/setup.py" }}
          paths:
            - "venv"
services:
  blockstack-core:
    image: 'quay.io/blockstack/blockstack-core:master'
    command: 'blockstack-core start --foreground --debug'
    volumes:
      - './data/core/server/:/root/.blockstack-server/'
      - './data/core/api/:/root/.blockstack/'
    restart: always
    ports:
      - "6264:6264"
    networks:
      - "api"
  blockstack-api:
    image: 'quay.io/blockstack/blockstack-core:master'
    command: blockstack api start-foreground -y --debug --password dummywalletpassword
    ports:
      - "6270:6270"
    volumes:
      - './data/api:/root/.blockstack'
      - './data/api/tmp:/tmp'
    environment:
      - BLOCKSTACK_CLIENT_INTERACTIVE_YES=0
    restart: always
    networks:
      - "api"
      
networks:
  api: null

      - run:
          command: |
            source venv/bin/activate
            blockstack setup -y --password Zhc6ikare
            blockstack api start -y --password Zhc6ikare
            python -m blockstack_integration_tests.live_tests.api_tests
            blockstack api stop -y
            cd tools/docker
            ./docker-tools.sh init-core
             ./docker-tools.sh init-api

# This docker-compose file is for spinning up a blockstack-core node and api
version: '2'
