[package]
name = "stacks-miner"
version = "0.1.0"
authors = ["Pascal Belloncle <psq@nanorails.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
pico-args = "0.3.1"
rand = "=0.7.2"
serde = "1"
serde_derive = "1"
serde_json = { version = "1.0", features = ["arbitrary_precision", "raw_value"] }
stacks = { package = "blockstack-core", path = "../../." }
#stacks-node = { package = "stacks-node", path = "../stacks-node/." }
toml = "0.5.6"
async-h1 = "=1.0"
async-std = { version = "<1.6", features = ["attributes"] }
http-types = "1.0"
base64 = "0.12.0"
backtrace = "0.3.50"
libc = "0.2"
log = "0.4.0"
env_logger = "0.8.2"

[dev-dependencies]
warp = "0.2"
tokio = "0.2.21"
reqwest = { version = "0.10", features = ["blocking", "json", "rustls"] }

[[bin]]
name = "stacks-miner"
path = "src/main.rs"

[features]
default = []
