name: PR Checks
on:
  pull_request:

jobs:
  clippy_check:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@v3
      - name: Define Rust Toolchain
        id: define_rust_toolchain
        run: echo "RUST_TOOLCHAIN=$(cat ./rust-toolchain)" >> $GITHUB_ENV
      - name: Setup Rust Toolchain
        id: setup_rust_toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy
      - name: Clippy
        id: clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  # Checked for leaked credentials if tag is provided and this is a build of the default branch
  leaked-cred-test:
    # if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    name: Leaked Credential Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@v3
      - name: PR branch name
        id: pr_extract_branch
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV
      - name: TruffleHog Scan
        id: trufflehog_check
        uses: trufflesecurity/trufflehog@v3.4.3
        with:
          path: ./
          base: ${{ env.BRANCH_NAME }}
          head: HEAD
