##
## Run tests for tagged releases
##

name: Tests

# Only run when:
#   - manually triggered via the ci.yml workflow

on:
  workflow_call:

jobs:
  # Run full genesis test
  full-genesis:
    name: Full Genesis Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@v3
      - name: Reclaim disk space
        id: cleanup
        run: |
          sudo apt-get update
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y '^mongodb-.*'
          sudo apt-get remove -y '^mysql-.*'
          sudo apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri
          sudo apt-get autoremove -y
          sudo apt-get clean
          docker system prune --force
      - name: Single full genesis integration test
        id: full_genesis_test
        env:
          DOCKER_BUILDKIT: 1
        # Remove .dockerignore file so codecov has access to git info
        run: |
          rm .dockerignore
          docker build -o coverage-output -f ./.github/actions/bitcoin-int-tests/Dockerfile.large-genesis .
      - name: Large Genesis Codecov
        id: full_genesis_codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage-output/lcov.info
          name: large_genesis
          fail_ci_if_error: false

  # Run unit tests with code coverage
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Add code coverage tools
        run: |
          rustup component add llvm-tools-preview
          cargo install grcov
      - name: Add nextest
        run: |
          cargo install cargo-nextest
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@v3
      - name: Run units tests (with coverage)
        id: unit_tests_codecov
        # unset the coverage instrumentation flags.
        # these slow tests down a lot locally (5-10x), and since
        # grcov cannot collect this coverage data right now anyways,
        # this is a speed win.
        #env:
        #  RUSTFLAGS: -Cinstrument-coverage
        #  LLVM_PROFILE_FILE: stacks-blockchain-%p-%m.profraw
        run: |
          cargo nextest run --workspace
          cargo nextest run --package clarity --features developer-mode
      - name: Collate grcov
        # grcov doesn't work with cargo nextest currently, getting
        #  that to work again will have to happen separately. Getting unit
        #  test run times below 2 hours is more important for now.
        if: ${{ false }}
        id: unit_tests_grcov
        env:
          RUSTFLAGS: -Cinstrument-coverage
          LLVM_PROFILE_FILE: stacks-blockchain-%p-%m.profraw
        run: |
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
      - name: Upload codecov results
        # grcov doesn't work with cargo nextest currently, getting
        #  that to work again will have to happen separately. Getting unit
        #  test run times below 2 hours is more important for now.
        if: ${{ false }}
        uses: codecov/codecov-action@v3
        id: codedov
        with:
          files: ./lcov.info
          name: unit_tests
          fail_ci_if_error: false

  open-api-validation:
    name: OpenAPI Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@v3
      - name: Run units tests (with coverage)
        id: api_codecov
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -o dist/ -f .github/actions/open-api/Dockerfile.open-api-validate .
      - name: Upload bundled html
        id: upload_html_artifact
        uses: actions/upload-artifact@v3
        with:
          name: open-api-bundle
          path: |
            dist

  # Run net-tests
  nettest:
    # disable this job/test for now, since we haven't seen this pass
    #  on github actions in a while, and the failures can take > 4 hours
    if: ${{ false }}
    name: Net-Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@v3
      - name: Run network relay tests
        id: nettest
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -f ./.github/actions/bitcoin-int-tests/Dockerfile.net-tests .

  # Core contract tests
  core-contracts-clarinet-test:
    name: Core Contracts Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        id: git_checkout
        uses: actions/checkout@v3
      - name: Execute core contract unit tests in Clarinet
        id: clarinet_unit_test
        uses: docker://hirosystems/clarinet:1.1.0
        with:
          args: test --coverage --manifest-path=./contrib/core-contract-tests/Clarinet.toml
      - name: Export code coverage
        id: clarinet_codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.lcov
          verbose: true
